---
name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What feature would you like to see?
    validations:
      required: true
